#!/bin/bash

# This script sets up all the config files once the directory is deployed

# Extracting script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo $SCRIPT_DIR

## Backup old config files
#export BACK_DIR="$DOT_DIR/backup/$(date +"%s")"
#echo "Backing up your config files at $BACK_DIR"
#mkdir -p $BACK_DIR
#find $SOURCERS_DIR -type f ! -name README.md -printf '%P\n' |
#    xargs -I [file] sh -c 'mkdir -p `dirname $BACK_DIR/[file]` &&
#        cp -v "$HOME/[file]" "$BACK_DIR/[file]" 2>/dev/null'
#
#find $LINK_DIR -type f ! -name README.md -printf '%P\n' |
#    xargs -I [file] sh -c 'mkdir -p `dirname $BACK_DIR/[file]` &&
#        cp -v "$HOME/[file]" "$BACK_DIR/[file]" 2>/dev/null'

echo "Running setup"
