#!/bin/sh

# upmi - Universal Package Manager Installer

# Don't use this script for anything serious plz



# Script need root acces or sudo access
if [[ $EUID -ne 0 ]]; then

    # Check is sudo is installed
    sudo -nv > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        >&2 echo "sudo is not installed or configured for current user"
    fi
    # else run commands using sudo
    PREFIX="sudo"
else
    unset PREFIX
fi

# Determine approprite package manager
guess_distribution()
{
    # https://unix.stackexchange.com/a/6348
    if [ -f /etc/os-release ]; then
        # freedesktop.org and systemd
        . /etc/os-release
        OS=$NAME
        VER=$VERSION_ID
    elif type lsb_release >/dev/null 2>&1; then
        # linuxbase.org
        OS=$(lsb_release -si)
        VER=$(lsb_release -sr)
    elif [ -f /etc/lsb-release ]; then
        # For some versions of Debian/Ubuntu without lsb_release command
        . /etc/lsb-release
        OS=$DISTRIB_ID
        VER=$DISTRIB_RELEASE
    elif [ -f /etc/debian_version ]; then
        # Older Debian/Ubuntu/etc.
        OS=Debian
        VER=$(cat /etc/debian_version)
    elif [ -f /etc/SuSe-release ]; then
        # Older SuSE/etc.
        ...
    elif [ -f /etc/redhat-release ]; then
        # Older Red Hat, CentOS, etc.
        ...
    else
        # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
        OS=$(uname -s)
        VER=$(uname -r)
    fi
}
